apiVersion: v1
kind: Secret
metadata:
  name: {{ include "accumulo.fullname" . }}-secrets
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  accumulo-username: {{ .Values.accumulo.username }}
  accumulo-password: {{ .Values.accumulo.password }}
  accumulo-instance-name: {{ .Values.accumulo.instanceName }}

